version: '3.5'
services:
    redis:
        container_name: vdtn359_redis
        image: redis:5-alpine
        volumes:
            - redis:/data
        ports:
            - '6379:6379'
        networks:
            - vdtn359_net_backend
    elasticsearch:
        image: elasticsearch:7.8.0
        environment:
            - cluster.name=news
            - bootstrap.memory_lock=true
            - discovery.type=single-node
            - node.name=vdtn359-news
            - xpack.license.self_generated.type=trial
            - xpack.security.enabled=false
            - xpack.monitoring.enabled=false
        volumes:
            - elasticsearch:/usr/share/elasticsearch/data
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - "9200:9200"
        networks:
            - vdtn359_net_backend
    kibana:
        image: kibana:7.6.2
        ports:
            - "5601:5601"
        networks:
            - vdtn359_net_backend

volumes:
    elasticsearch:
        name: vdtn359_volume_elasticsearch
    redis:
        name: vdtn359_volume_redis
networks:
    vdtn359_net_backend:
        driver: bridge
